### ISSUE TITLE
Drush error: TLS/SSL error: SSL is required, but the server does not support it

### ISSUE THREAD

**Issue by jurgenhaas** [wodby/drupal-php#104]
I've updated to the latest image for PHP 8.3 this morning and now get the `TLS/SSL error: SSL is required, but the server does not support it` error when running `drush sqlc`. When I downgrade the image to the one before, the error goes away.

What's interesting, the PHP-FPM can access the the database with the same credentials without an issue. The mariadb CLI can not and gets the same error message.

Any idea what's wrong here?

**Comment by jurgenhaas** [comment]
Hmm, I've experimented with the `MARIADB_CLIENT_SSL_VERIFY_SERVER_CERT` env variable, but it doesn't seem to change anything. What's the purpose of that?

**Comment by jurgenhaas** [comment]
Ah, I see you only committed that a few minutes ago.

Adding that `disable-ssl-verify-server-cert` manually to the client config. That works for the mariadb cli in the PHP container, but it doesn't work for Drush, unfortunately.

**Comment by csandanov** [comment]
Does it work if you replace `[client-mariadb]` with the `[client]`?

**Comment by jurgenhaas** [comment]
Unfortunately not. The command drush executes looks like this:

```
mysql --defaults-file=/tmp/drush_BHJImp --database=drupal --host=mariadb --port=3306 --silent -A < /tmp/drush_JeoAmp
```

Is the `--default-file` probably overriding the system conf?

**Comment by weitzman** [comment]
If you run the drush sql command with --show-passwords option, then it wont use --defaults-file. If that works, lets discuss how to remedy.

**Comment by jurgenhaas** [comment]
Yes, I've tried that and it works.

**Comment by jurgenhaas** [comment]
Oh, wait. It seems to work for `sqlq` but not for `sqlc`. Doing more testing ...

**Comment by jurgenhaas** [comment]
Hmm, that seems to be correct as I stated. For `sqlq` Drush calls `mysql` and then `mariadb`, both times by showing the password.

For `sqlc` Drush calls `mysql` first by showing the password and then it calls `mariadb` by using the default file.

**Comment by weitzman** [comment]
OK, thats a small bug in sqlc. Lets use sqlq to figure out best way forward. Its been a while since I researched merging of [client] config in a my.cnf file. I dunno whats possible with --defaults-file and such. For the Drush history here, see https://github.com/drush-ops/drush/pull/2387 and its linked issues.

**Comment by jurgenhaas** [comment]
Phew, that's beyond my horizon right now. But I'd be happy to test if anything is around.

**Comment by csandanov** [comment]
4.65.1 is the tag with `disable-ssl-verify-server-cert` for mariadb client

**Comment by back-2-95** [comment]
I can confirm importing a dump with `drush sql-query --show-passwords ... ` worked.

**Comment by ChristopheCARONMGDIS** [comment]
In my case I used tag 8.1-dev and I had always error with drush sql-drop or drush sql-cli, i needed to use --extra=--skip-ssl

**Comment by ChristopheCARONMGDIS** [comment]
Error is too present for drush sql-drop (drop doesn't work, --extra is not available ! ) and drush sql-dump too.
To avoid errors we need to use:
drush sql-dump --extra-dump=--skip-ssl > ./dump.sql

How to setup env to skip this error globally ?

**Comment by gyurix1968** [comment]
> Error is too present for drush sql-drop (drop doesn't work, --extra is not available ! ) and drush sql-dump too. To avoid errors we need to use: drush sql-dump --extra-dump=--skip-ssl > ./dump.sql
> 
> How to setup env to skip this error globally ?

You can use it '--skip-ssl' parameter instead of any '--extra' flag.

**Comment by gene-miller** [comment]
This also breaks `drush si` with no workaround that I can find.

 Upgrading mariadb to 11.4 solves the issue, but that is not available on the Wodby platform currently.

Is it possible to downgrade the mariadb client in the PHP image?

**Comment by szeidler** [comment]
> Upgrading mariadb to 11.4 solves the issue, but that is not available on the Wodby platform currently.

The upgrade should be possible now with the recent stacks.

**Comment by jurgenhaas** [comment]
@szeidler that's great news. Had it been fixed in the wodby stack or is it due to the latest drush release?

**Comment by szeidler** [comment]
The latest Drush release 13.4.0 did not fix the `TLS/SSL error: SSL is required, but the server does not support it` that got reported here. So right now you would still need the `--skip-ssl`.

If you're using Docker4Drupal or Wodby Stacks MariaDB 11.4 is available now. If you use it, then it works as expected without any necessary workaround, also with Drush versions before 13.4.0. Probably because the mariadb-client version from Alpine is in sync with your mariadb server then.

**Comment by jurgenhaas** [comment]
Sounds great, I'll give that a try.
